[[services]]
name = "Ngrok-Service"
dockerfile = "Dockerfile"

[services.env]
NGROK_AUTHTOKEN = "${NGROK_AUTHTOKEN}"
PORT = "80"
# Optional: Set your custom domain
# NGROK_URL = "thankfully-innocent-llama.ngrok-free.app"
